apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: marciasheilapipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: marciasheilapipelinesjavascriptdocker 
    spec:
      containers:
        - name: marciasheilapipelinesjavascriptdocker 
          image: mspgcontainerregistry.azurecr.io/marciasheilapipelinesjavascriptdocker
          ports:
          - containerPort: 8080